name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Run Unit Tests
      with:
        node-version: 14.x
    - run: npm i
    - run: npm run test:unit
